# Generated by Django 3.1.7 on 2021-03-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('courseDescription', models.CharField(max_length=100)),
                ('lecturerName', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('seatsAvailable', models.CharField(max_length=100)),
                ('credits', models.CharField(max_length=100)),
                ('enrolled', models.CharField(max_length=100)),
            ],
        ),
    ]
